### ISSUE TITLE
HTTP page

### ISSUE THREAD

**Issue by xolmuhammedov** [ShukhratbekDev/nimau#3]
i couldn't find the error why vercel is rejected my request

**Comment by ShukhratbekDev** [comment]
Hi @xolmuhammedov  please rebase your branch, I've pushed a lot of changes.And could you please read this article https://www.nimau.uz/blog/how-to-create-doc . As I see you have missed https://fumadocs.vercel.app/docs/headless/page-conventions#frontmatter.

The error screenshot I've shared on your MR
